# Generated by Django 2.0.7 on 2018-07-09 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='stock_id',
            new_name='stock',
        ),
    ]
