# Generated by Django 2.0.7 on 2018-07-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0003_auto_20180709_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buy_sell_flag',
        ),
        migrations.AddField(
            model_name='stock',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockprices',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.Stock'),
        ),
    ]
