# Generated by Django 2.0.7 on 2018-07-09 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0005_transaction_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='holdings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AMS.Holdings'),
        ),
    ]
