# Generated by Django 2.0.7 on 2018-07-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0006_transaction_holdings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stock',
        ),
    ]
