# Generated by Django 2.0.7 on 2018-07-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0007_auto_20180709_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdings',
            name='value',
        ),
        migrations.AlterField(
            model_name='stockprices',
            name='date',
            field=models.DateField(default=0),
        ),
    ]
